### ISSUE TITLE
Update ESLint config when eslint-plugin-import is updated

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#199]
After https://github.com/votingworks/bmd/pull/174 is merged and once `eslint-plugin-import` is updated…

# Issues/PRs
https://github.com/benmosher/eslint-plugin-import/issues/1120
https://github.com/benmosher/eslint-plugin-import/issues/1282
https://github.com/benmosher/eslint-plugin-import/pull/1304

## TODO
- [x] upgrade `eslint-plugin-import`. Current version:`2.16.0`.
- [x] remove `typescript-eslint-parser`
- [ ] remove workaround using: `jsExtensions`, `tsExtensions`, `allExtensions` 
- [x] remove `// eslint-disable-line import/named` from all `type` exports
