### ISSUE TITLE
Display Election Title and Date on Admin Screen

### ISSUE THREAD

**Issue by beausmith** [votingworks/bmd#664]
## Goal
This is to confirm to Admin that they have loaded the correct election.

## Tasks
- [ ] Display Election Title on Admin Screen.
- [ ] Display Election Date on Admin Screen
  - [ ] If election is in the past, display a warning: `This election is for MMMM D, YYYY, which is in the past.`

**Comment by beausmith** [comment]
I think we'll want the "election is in the past" warning, too. -@benadida

**Comment by beausmith** [comment]
Past Election warning moved to separate issue: https://github.com/votingworks/bmd/issues/813
